config/routes.rb
Rails.application.routes.draw do

  post   'post'   => 'entries#create'
  get 'blog'  => 'entries#index'
  get 'write' => 'entries#new'
  
  get 'portfolio' => 'projects#index'
  get 'create' => 'projects#new'
  post 'render' => 'projects#create'
  
  get 'sessions/new'

  root 'sessions#new'
  get 'signup' => 'users#new'
  get 'home' => 'static_pages#home'
  get 'admin' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :entries
  resources :projects

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 30 }
  validates :main_image, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 30 }
  validates :main_image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :destroy]
  
  def index
    store_location
    if logged_in?
      @logged_in = true
    end
    @entries = Entry.paginate(page: params[:page], :per_page => 8)
  end

  def show
    store_location
    if logged_in?
      @logged_in = true
    end
    @entry = Entry.find(params[:id])
  end

  def edit
    store_location
    @entry = Entry.find(params[:id])
  end

  def new
    store_location
    @entry = Entry.new
  end
  
  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:success] = "Entry posted successfully!"
      redirect_to blog_path
    else
      render 'new'
    end
  end
  
  def update
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(entry_params)
      flash[:success] = "Entry updated"
      redirect_to @entry
    else
      render 'edit'
    end
  end
    
  def destroy
  end
    
    private

    def entry_params
      params.require(:entry).permit(:title, :main_image, :photo_one, :photo_two,
                                   :photo_three, :photo_four, :para_one,
                                   :para_two, :para_three, :para_four, :blurb)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :destroy]
  
  def index
    store_location
    if logged_in?
      @logged_in = true
    end
    @projects = Project.paginate(page: params[:page], :per_page => 8)
  end

  def show
    store_location
    if logged_in?
      @logged_in = true
    end
    @project = Project.find(params[:id])
  end

  def edit
    store_location
    @project = Project.find(params[:id])
  end

  def new
    store_location
    @project = Project.new
  end
  
  def create
    store_location
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Project created successfully!"
      redirect_to portfolio_path
    else
      render 'new'
    end
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Project updated"
      redirect_to @project
    else
      render 'edit'
    end
  end
    
  def destroy
  end
    
    private

    def project_params
      params.require(:project).permit(:title, :main_image, :image_one, :image_two,
                                   :image_three, :desc_one, :desc_two,
                                   :desc_three, :blurb)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @users = User.all
  end

  def create
    store_location
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Incorrect credentials.'
      @users = User.all
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_back_or root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :user_created, only: [:new]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    if !User.exists?(1)
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome to Monolace!"
        redirect_to @user
      else
        render 'new'
      end
    else
      flash[:danger] = "Site has already been claimed."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Before filters

    # Checks if user exists
    def user_created
      if User.exists?(1)
        flash[:danger] = "This site has already been claimed."
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    store_location
    session.delete(:user_id)
    @current_user = nil
  end
  
  #before filters
  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in to access this page."
        redirect_to admin_url
      end
    end


# Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_entry.html.erb
<div class='row' id="entry-<%= entry.id %>">
  <div class='col-sm-12 single-entry'>
    <%= link_to (image_tag entry.main_image, class: 'cover'), entry %>
    <h1 class="title"><%= link_to entry.title, entry, class:'entry-link' %></h1>
    <h2 class="timestamp">Posted <%= time_ago_in_words(entry.created_at) %> ago.</h2>
    <% if @logged_in %>
      <p class='edit'><%= link_to 'Edit', edit_entry_path(:id => entry.id) %></p>
    <% end %>
  </div>
</div>

app/views/entries/destroy.html.erb
<h1>Entries#destroy</h1>
<p>Find me in app/views/entries/destroy.html.erb</p>

app/views/entries/edit.html.erb
<% provide(:title, "Edit Entry") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to '< Back', blog_path %>
    <h1>Edit Entry</h1>
    <%= form_for(@entry) do |f| %>

      <%= f.label :title %> <span style='color:red;'>*</span>
      <%= f.text_field :title, class: 'form-control', :placeholder => "what should we call this?" %>

      <%= f.label :main_image %> <span style='color:red;'>*</span>
      <%= f.text_field :main_image, class: 'form-control', :placeholder => "main image url" %>
      
      <hr />
      
      <%= f.label :blurb %>
      <%= f.text_area :blurb, class: 'form-control', :placeholder => "entry overview" %>
      
      <hr />
      
      <%= f.label :photo_one, 'Image (1)' %>
      <%= f.text_field :photo_one, class: 'form-control', :placeholder => "image url" %>
      
      <%= f.label :para_one, 'First Paragraph' %>
      <%= f.text_area :para_one, class: 'form-control', :placeholder => "a bit about image one" %>
      
      <hr />
      
      <%= f.label :photo_two, 'Image (2)' %>
      <%= f.text_field :photo_two, class: 'form-control' %>
      
      <%= f.label :para_two, 'Second Paragraph' %>
      <%= f.text_area :para_two, class: 'form-control' %>
      
      <hr />
      
      <%= f.label :photo_three, 'Image (3)' %>
      <%= f.text_field :photo_three, class: 'form-control' %>
      
      <%= f.label :para_three, 'Third Paragraph' %>
      <%= f.text_area :para_three, class: 'form-control' %>
      
      <hr />
      
      <%= f.label :photo_four, 'Image (4)' %>
      <%= f.text_field :photo_four, class: 'form-control' %>
      
      <%= f.label :para_four, 'Fourth Paragraph' %>
      <%= f.text_area :para_four, class: 'form-control' %>
      
      <hr />
      <span style='color:red;'>*</span> required
      <br />
      <br />
      
      <%= f.submit "Post", class: "btn btn-primary" %>
      <br>
    <% end %>
  </div>
</div>

app/views/entries/index.html.erb
<% provide(:title, 'Blog') %>
<h1>Blog</h1>
<% if @logged_in %>
  <h3><%= link_to 'New Entry', new_entry_path, class: 'project-edit' %></h3>
<% end %>

<br />

<div class="container-fluid">
  <%= render @entries %>
</div>

<%= will_paginate %>

app/views/entries/new.html.erb
<% provide(:title, "New Entry") %>
<h1>New Entry</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@entry, url: post_path) do |f| %>

      <%= f.label :title %> <span style='color:red;'>*</span>
      <%= f.text_field :title, class: 'form-control', :placeholder => "what should we call this?" %>

      <%= f.label :main_image %> <span style='color:red;'>*</span>
      <%= f.text_field :main_image, class: 'form-control', :placeholder => "main image url" %>
      
      <hr />
      
      <%= f.label :blurb %>
      <%= f.text_area :blurb, class: 'form-control', :placeholder => "entry overview" %>
      
      <hr />
      
      <%= f.label :photo_one, 'Image (1)' %>
      <%= f.text_field :photo_one, class: 'form-control', :placeholder => "image url" %>
      
      <%= f.label :para_one, 'First Paragraph' %>
      <%= f.text_area :para_one, class: 'form-control', :placeholder => "a bit about image one" %>
      
      <hr />
      
      <%= f.label :photo_two, 'Image (2)' %>
      <%= f.text_field :photo_two, class: 'form-control' %>
      
      <%= f.label :para_two, 'Second Paragraph' %>
      <%= f.text_area :para_two, class: 'form-control' %>
      
      <hr />
      
      <%= f.label :photo_three, 'Image (3)' %>
      <%= f.text_field :photo_three, class: 'form-control' %>
      
      <%= f.label :para_three, 'Third Paragraph' %>
      <%= f.text_area :para_three, class: 'form-control' %>
      
      <hr />
      
      <%= f.label :photo_four, 'Image (4)' %>
      <%= f.text_field :photo_four, class: 'form-control' %>
      
      <%= f.label :para_four, 'Fourth Paragraph' %>
      <%= f.text_area :para_four, class: 'form-control' %>
      
      <hr />
      <span style='color:red;'>*</span> required
      <br />
      <br />
      
      <%= f.submit "Post", class: "btn btn-primary" %>
      <br>
    <% end %>
  </div>
</div>

app/views/entries/show.html.erb
<h1><%= @entry.title %></h1>
<% if @logged_in %>
  <h2> <%=link_to 'Edit entry', edit_entry_path %></h2>
<% end %>
<h2><%= image_tag @entry.main_image, class: 'cover' %></h2>

<% if !@entry.blurb.blank? %>
    <h3><%= @entry.blurb %></h3>
<% end %>

<hr />

<% if !@entry.photo_one.blank? %>
    <h2><%= image_tag @entry.photo_one, class: 'cover'  %></h2>
<% end %>

<% if !@entry.para_one.blank? %>
    <h2><%= @entry.para_one %></h2>
    <hr />
<% end %>

<% if !@entry.photo_two.blank? %>
    <h2><%= image_tag @entry.photo_two, class: 'cover'  %></h2>
<% end %>

<% if !@entry.para_two.blank? %>
    <h2><%= @entry.para_two %></h2>
    <hr />
<% end %>

<% if !@entry.photo_three.blank? %>
    <h2><%= image_tag @entry.photo_three, class: 'cover'  %></h2>
<% end %>

<% if !@entry.para_three.blank? %>
    <h2><%= @entry.para_three %></h2>
    <hr />
<% end %>

<% if !@entry.photo_four.blank? %>
    <h2><%= image_tag @entry.photo_four, class: 'cover'  %></h2>
<% end %>

<% if !@entry.para_four.blank? %>
    <h2><%= @entry.para_four %></h2>
    <hr />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright 2016 Jacob Hardbower
  </small>
  <nav>
    <ul>
      <li><%= link_to "Entries",   entries_path %></li>
      <li><%= link_to "Projects", projects_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Monolace", "http://www.monolace.hardbower.com", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Projects",    projects_path %></li>
        <li><%= link_to "Entries",    entries_path %></li>
        <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Content <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create Entry", write_path %></li>
              <li><%= link_to "Create Project", create_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Edit Entries", entries_path %></li>
              <li><%= link_to "Edit Projects", projects_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", admin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/projects/_project.html.erb
<div id="project-<%= project.id %>">
  <div class='single-project'>
    <%= link_to (image_tag project.main_image, class: 'project-hero'), project %>
    <p class='project-title'><%= link_to project.title, project %></p>
    <% if @logged_in %>
      <p class='project-edit'><%= link_to 'Edit', edit_project_path(:id => project.id) %></p>
    <% end %>
  </div>
</div>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<% provide(:title, "Edit Project") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to '< Back', portfolio_path %>
    <h1>Edit Project</h1>
    <h2>- <%= @project.title %> -</h2>
    <%= form_for(@project) do |f| %>

      <%= f.label :title %> <span style='color:red;'>*</span>
      <%= f.text_field :title, class: 'form-control', :placeholder => "what should we call this?" %>

      <%= f.label :main_image %> <span style='color:red;'>*</span>
      <%= f.text_field :main_image, class: 'form-control', :placeholder => "main image url" %>
      
      <hr />
      
      <%= f.label :blurb %>
      <%= f.text_area :blurb, class: 'form-control', :placeholder => "project overview" %>
      
      <hr />
      
      <%= f.label :image_one, 'Image (1)' %>
      <%= f.text_field :image_one, class: 'form-control', :placeholder => "image url" %>
      
      <%= f.label :desc_one, 'Description' %>
      <%= f.text_area :desc_one, class: 'form-control', :placeholder => "a short description" %>
      
      <hr />
      
      <%= f.label :image_two, 'Image (2)' %>
      <%= f.text_field :image_two, class: 'form-control' %>
      
      <%= f.label :desc_two, 'Description' %>
      <%= f.text_area :desc_two, class: 'form-control' %>
      
      <hr />
      
      <%= f.label :image_three, 'Image (3)' %>
      <%= f.text_field :image_three, class: 'form-control' %>
      
      <%= f.label :desc_three, 'Description' %>
      <%= f.text_area :desc_three, class: 'form-control' %>
      
      <hr />
      
      <span style='color:red;'>*</span> required
      
      <br />
      <br />
      
      <%= f.submit "Post", class: "btn btn-primary" %>
      <br>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'Portfolio') %>
<h1>Portfolio</h1>
<% if @logged_in %>
  <h3><%= link_to 'New Project', new_project_path, class: 'project-edit' %></h3>
<% end %>

<br />

<div>
  <%= render @projects %>
</div>

<br class='clearboth'>

<%= will_paginate %>

app/views/projects/new.html.erb
<% provide(:title, "New Project") %>
<h1>New Project</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project, url: render_path) do |f| %>

      <%= f.label :title %> <span style='color:red;'>*</span>
      <%= f.text_field :title, class: 'form-control', :placeholder => "what should we call this?" %>

      <%= f.label :main_image %> <span style='color:red;'>*</span>
      <%= f.text_field :main_image, class: 'form-control', :placeholder => "main image url" %>
      
      <hr />
      
      <%= f.label :blurb %>
      <%= f.text_area :blurb, class: 'form-control', :placeholder => "project overview" %>
      
      <hr />
      
      <%= f.label :image_one, 'Image (1)' %>
      <%= f.text_field :image_one, class: 'form-control', :placeholder => "image url" %>
      
      <%= f.label :desc_one, 'Description' %>
      <%= f.text_area :desc_one, class: 'form-control', :placeholder => "a short description" %>
      
      <hr />
      
      <%= f.label :image_two, 'Image (2)' %>
      <%= f.text_field :image_two, class: 'form-control' %>
      
      <%= f.label :desc_two, 'Description' %>
      <%= f.text_area :desc_two, class: 'form-control' %>
      
      <hr />
      
      <%= f.label :image_three, 'Image (3)' %>
      <%= f.text_field :image_three, class: 'form-control' %>
      
      <%= f.label :desc_three, 'Description' %>
      <%= f.text_area :desc_three, class: 'form-control' %>
      
      <hr />
      
      <span style='color:red;'>*</span> required
      
      <br />
      <br />
      
      <%= f.submit "Post", class: "btn btn-primary" %>
      <br>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<% if @logged_in %>
  <h2> <%=link_to 'Edit entry', edit_project_path %></h2>
<% end %>
<div class='cover-holder'><%= image_tag @project.main_image, class: 'cover-image' %></div>

<% if !@project.blurb.blank? %>
    <h3><%= @project.blurb %></h3>
<% end %>

<hr />

<% if !@project.image_one.blank? %>
    <h2><%= image_tag @project.image_one, class: 'show-project-image' %></h2>
<% end %>

<% if !@project.desc_one.blank? %>
    <h2><%= @project.desc_one %></h2>
    <hr />
<% end %>

<% if !@project.image_two.blank? %>
    <h2><%= image_tag @project.image_two, class: 'show-project-image' %></h2>
<% end %>

<% if !@project.desc_two.blank? %>
    <h2><%= @project.desc_two %></h2>
    <hr />
<% end %>

<% if !@project.image_three.blank? %>
    <h2><%= image_tag @project.image_three, class: 'show-project-image' %></h2>
<% end %>

<% if !@project.desc_three.blank? %>
    <h2><%= @project.desc_three %></h2>
    <hr />
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Settings") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Create Account') %>
<h1>Create your account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>